import os
import re
import shutil
import json
from typing import List

# Target directory is locked strictly to the project execution directory
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))


def _sanitize_db_name(db_name: str) -> str:
    """Sanitizes database name input and ensures proper .json extension."""
    clean_name = db_name.strip()
    # Remove path traversal characters or invalid filename symbols
    clean_name = re.sub(r'[\\/:*?"<>|]', '', clean_name)
    if not clean_name.lower().endswith('.json'):
        clean_name += '.json'
    return clean_name


def database_exists(db_name: str) -> bool:
    """Checks if a database file exists in the project directory (case-insensitive)."""
    sanitized_name = _sanitize_db_name(db_name).lower()
    try:
        # Scan project directory for exact or case-insensitive matches
        for entry in os.scandir(PROJECT_DIR):
            if entry.is_file() and entry.name.lower() == sanitized_name:
                return True
    except OSError:
        pass
    return False


def list_databases() -> List[str]:
    """
    Lists all database JSON files in the project directory.
    Uses os.scandir with os.listdir fallback for system resilience.
    """
    db_files = []
    
    # Primary Method: os.scandir
    try:
        with os.scandir(PROJECT_DIR) as entries:
            for entry in entries:
                if entry.is_file() and entry.name.lower().endswith('.json'):
                    # Exclude temporary or backup files generated by flatDB
                    if not (entry.name.endswith('.tmp') or entry.name.endswith('.bak')):
                        db_files.append(entry.name)
        return sorted(db_files)
    except OSError:
        pass

    # Fallback Method: os.listdir
    try:
        all_files = os.listdir(PROJECT_DIR)
        for filename in all_files:
            if filename.lower().endswith('.json') and not (filename.endswith('.tmp') or filename.endswith('.bak')):
                full_path = os.path.join(PROJECT_DIR, filename)
                if os.path.isfile(full_path):
                    db_files.append(filename)
        return sorted(db_files)
    except OSError:
        return []


def create_database(db_name: str) -> str:
    """
    Creates a new database JSON file with empty schema and data structure.
    Uses atomic exclusive creation ('x' mode) to prevent race-condition overwrites.
    
    Returns created database filename.
    """
    filename = _sanitize_db_name(db_name)
    filepath = os.path.join(PROJECT_DIR, filename)

    if database_exists(filename):
        raise FileExistsError(f"Database '{filename}' already exists in the project directory.")

    initial_payload = {
        "schema": {},
        "data": []
    }

    try:
        # Exclusive atomic open: Fails if file was created concurrently between check and open
        with open(filepath, 'x', encoding='utf-8') as f:
            json.dump(initial_payload, f, indent=2)
            f.flush()
            os.fsync(f.fileno())
        return filename
    except FileExistsError:
        raise FileExistsError(f"Database '{filename}' already exists.")
    except Exception as e:
        # Clean up partial zero-byte file if creation failed halfway
        if os.path.exists(filepath):
            try:
                os.remove(filepath)
            except OSError:
                pass
        raise IOError(f"Failed to create database file '{filename}': {e}")


def rename_database(old_name: str, new_name: str) -> str:
    """
    Renames an existing database file in the project directory.
    Includes copy-and-delete fallback if os.rename fails (e.g., Windows file locks).
    
    Returns the new database filename.
    """
    old_filename = _sanitize_db_name(old_name)
    new_filename = _sanitize_db_name(new_name)

    old_path = os.path.join(PROJECT_DIR, old_filename)
    new_path = os.path.join(PROJECT_DIR, new_filename)

    if not os.path.exists(old_path):
        raise FileNotFoundError(f"Source database '{old_filename}' does not exist.")

    if old_filename.lower() != new_filename.lower() and database_exists(new_filename):
        raise FileExistsError(f"Target database name '{new_filename}' is already in use.")

    # Primary Rename Attempt
    try:
        os.rename(old_path, new_path)
        _rename_associated_backups(old_path, new_path)
        return new_filename
    except OSError:
        pass

    # Fallback Strategy: Copy-then-Delete
    try:
        shutil.copy2(old_path, new_path)
        if os.path.exists(new_path) and os.path.getsize(new_path) == os.path.getsize(old_path):
            os.remove(old_path)
            _rename_associated_backups(old_path, new_path)
            return new_filename
        else:
            raise IOError("Copy validation failed during fallback rename.")
    except Exception as e:
        # Cleanup orphan target if copy failed
        if os.path.exists(new_path) and old_filename.lower() != new_filename.lower():
            try:
                os.remove(new_path)
            except OSError:
                pass
        raise IOError(f"Could not rename database '{old_filename}' to '{new_filename}': {e}")


def _rename_associated_backups(old_base_path: str, new_base_path: str) -> None:
    """Helper to rename matching .bak and .tmp files alongside the main database file."""
    for ext in ['.bak', '.tmp']:
        old_aux = f"{old_base_path}{ext}"
        new_aux = f"{new_base_path}{ext}"
        if os.path.exists(old_aux):
            try:
                os.replace(old_aux, new_aux)
            except OSError:
                pass
